INSERT INTO automation.accounts (gender,
                                 firstCustomerName,
                                 lastCustomerName,
                                 pass,
                                 email,
                                 day,
                                 month,
                                 year,
                                 firstName,
                                 lastName,
                                 company,
                                 address1,
                                 address2,
                                 city,
                                 state,
                                 postcode,
                                 country,
                                 phone_mobile,
                                 alias)
VALUES ("Mr.", "Jack", "Daniels","Jack.Daniels", "Jack.DanielsSmFjay5EYW5pZWxzCk5hcGEuVmFsbGV5CkdyZXkuR29vc2U=@gmail.com", "8", "8", "1987", "Yakov", "Fayn", "IBM",
        "San Francisco 1", "Moscow 2", "London", "Alabama", "02206", "United States", "+30995652333", "Alloha!"),
       ("Mrs.", "Napa", "Valley", "Napa.Valley", "Napa.ValleySmFjay5EYW5pZWxzCk5hcGEuVmFsbGV5CkdyZXkuR29vc2U=@gmail.com", "8", "8", "1987", "Yakov", "Fayn", "IBM",
        "San Francisco 1", "Moscow 2", "London", "Alabama", "02206", "United States", "+30995652333", "Alloha!"),
       ("Mr.", "Grey", "Goose", "Grey.Goose", "Grey.GooseSmFjay5EYW5pZWxzCk5hcGEuVmFsbGV5CkdyZXkuR29vc2U=@gmail.com", "8", "8", "1987", "Yakov", "Fayn", "IBM",
        "San Francisco 1", "Moscow 2", "London", "Alabama", "02206", "United States", "+30995652333", "Alloha!");